// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCePZCkRHLM94pj3LA57p83hfdxQ1aCzik',
    appId: '1:445204037763:web:a0a70a80a951d8adb85bb6',
    messagingSenderId: '445204037763',
    projectId: 'noteapp-8a06c',
    authDomain: 'noteapp-8a06c.firebaseapp.com',
    storageBucket: 'noteapp-8a06c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzeDDwrT_9bfj0F13XL8btMY4Q_PxDa4',
    appId: '1:445204037763:android:d189ac6c4f15a6a0b85bb6',
    messagingSenderId: '445204037763',
    projectId: 'noteapp-8a06c',
    storageBucket: 'noteapp-8a06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakRh5VwitCP5OoDjy3jyEZ73CT5k_b4g',
    appId: '1:445204037763:ios:24bc45eea27735c1b85bb6',
    messagingSenderId: '445204037763',
    projectId: 'noteapp-8a06c',
    storageBucket: 'noteapp-8a06c.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDakRh5VwitCP5OoDjy3jyEZ73CT5k_b4g',
    appId: '1:445204037763:ios:b8ae3e5e367fd672b85bb6',
    messagingSenderId: '445204037763',
    projectId: 'noteapp-8a06c',
    storageBucket: 'noteapp-8a06c.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
